"""Which build is running has to be answerable from the app itself.

Four .exe files shipped in one afternoon, every one reporting `0.1.0`. When the
operator says "it still says permission denied", that could mean the fix did not
work or that the old binary is still installed, and nothing on screen told them
apart. Every follow-up question was then unanswerable.
"""

from __future__ import annotations

import json

import pytest

from ev_proposal_agent import buildinfo


def test_label_is_honest_about_running_from_source(monkeypatch, tmp_path):
    """No stamp file means not packaged. Say so rather than implying a build."""
    monkeypatch.setattr(buildinfo, "BUILD_INFO", tmp_path / "absent.json")
    assert buildinfo.build_info()["stamp"] == "dev"
    assert "from source" in buildinfo.build_label()


def test_label_reports_the_packaged_stamp(monkeypatch, tmp_path):
    stamp = tmp_path / "build_info.json"
    stamp.write_text(json.dumps({
        "version": "9.9.9", "built": "2026-01-02 03:04", "stamp": "feedface",
    }), encoding="utf-8")
    monkeypatch.setattr(buildinfo, "BUILD_INFO", stamp)
    label = buildinfo.build_label()
    assert "9.9.9" in label and "2026-01-02 03:04" in label and "feedface" in label


def test_corrupt_stamp_never_raises(monkeypatch, tmp_path):
    """It is a label on a window. It must not be able to stop the app opening."""
    bad = tmp_path / "build_info.json"
    bad.write_text("{not json", encoding="utf-8")
    monkeypatch.setattr(buildinfo, "BUILD_INFO", bad)
    assert buildinfo.build_label()          # falls back, does not explode


def test_the_stamp_tracks_content_not_the_clock():
    """Two builds a minute apart look identical by timestamp. The stamp is what
    answers "is my fix in this one", so it must hash the inputs."""
    from tools import stamp_build

    first = stamp_build.content_stamp()
    assert len(first) == 8
    assert first == stamp_build.content_stamp()          # deterministic

    target = next(p for p in stamp_build.INPUTS if p.suffix == ".py" and p.exists())
    original = target.read_bytes()
    try:
        target.write_bytes(original + b"\n# nudge\n")
        assert stamp_build.content_stamp() != first      # content moved
    finally:
        target.write_bytes(original)
    assert stamp_build.content_stamp() == first          # and back again


def test_the_field_map_and_template_are_in_the_stamp():
    """They are bundled into the exe and change its output, so a build that
    differs only by template must report a different stamp."""
    from tools import stamp_build

    names = [p.name for p in stamp_build.INPUTS]
    assert "field_map.yaml" in names
    assert "proposal_template.docx" in names


def test_qa_report_names_the_build(best_western_context, field_map):
    from ev_proposal_agent.validate import qa_report, validate

    text = qa_report(best_western_context, validate(best_western_context, field_map))
    assert "Generated by" in text
    assert buildinfo.build_label() in text
