// GENERATED by scripts/import-intake-refdata.py — do not edit by hand.
// Chargetronix price book: SKUs, per-class service and warranty rates, equipment architecture.
// Source: EVSE_Project_Intake_TEMPLATE_3.2.0.xlsx (EVSE Project Intake template 3.2.0,
// released 2026-09-04, content hash b0140566d4234d54). Generated 2026-09-11.
// Re-run `npm run refdata` when the CEO releases a new template.

export const REFDATA_META = {
  "templateVersion": "3.2.0",
  "released": "2026-09-04",
  "contentHash": "b0140566d4234d54",
  "sourceFile": "EVSE_Project_Intake_TEMPLATE_3.2.0.xlsx",
  "generatedAt": "2026-09-11"
} as const;

export type SkuRole = "all_in_one" | "power_cabinet" | "dispenser" | "level_2" | "accessory";

export interface PriceBookSku {
  sku: string;
  /** Raw price-book category, e.g. "_kW240", "_L2", "_Buy_America". */
  category: string;
  /** Capacity picker label the SKU sits under, e.g. "240 kW DC", "Level 2 AC". */
  capacity: string;
  description: string;
  /** Manufacturer list price, before the Commercial-tab discount. */
  msrp: number;
  /** Rated kW (DC output for chargers; 7.2 for Level 2; 0 for accessories). */
  ratedKw: number;
  /** Charging connectors — 0 for power cabinets (their dispensers carry them) and accessories. */
  connectors: number;
  connectorBasis: string;
  role: SkuRole;
}

export const PRICE_BOOK: PriceBookSku[] = [
  {"sku": "CTX-R40-240-1", "category": "_L2", "capacity": "Level 2 AC", "description": "40A Single Home Charger", "msrp": 605, "ratedKw": 7.2, "connectors": 1, "connectorBasis": "description says Single", "role": "level_2"},
  {"sku": "CTX-R48-240-1", "category": "_L2", "capacity": "Level 2 AC", "description": "48A Single Home Charger", "msrp": 605, "ratedKw": 7.2, "connectors": 1, "connectorBasis": "description says Single", "role": "level_2"},
  {"sku": "CTX-C32-240-1", "category": "_L2", "capacity": "Level 2 AC", "description": "32A Single Commercial L2 Charger", "msrp": 1402.5, "ratedKw": 7.2, "connectors": 1, "connectorBasis": "description says Single", "role": "level_2"},
  {"sku": "CTX-C48-240-1", "category": "_L2", "capacity": "Level 2 AC", "description": "48A Single Commercial L2 Charger (18' Cable with Modem)", "msrp": 1402.5, "ratedKw": 7.2, "connectors": 1, "connectorBasis": "description says Single", "role": "level_2"},
  {"sku": "CTX-C80-240-1", "category": "_L2", "capacity": "Level 2 AC", "description": "80A Single Commercial L2 Charger (18' Cable with Modem)", "msrp": 1650, "ratedKw": 7.2, "connectors": 1, "connectorBasis": "description says Single", "role": "level_2"},
  {"sku": "CTX-C40-240-2", "category": "_L2", "capacity": "Level 2 AC", "description": "40A Dual Commercial L2 Charger (18' Cable with Modem)", "msrp": 1952.5, "ratedKw": 7.2, "connectors": 2, "connectorBasis": "description says Dual", "role": "level_2"},
  {"sku": "CTX-C80-240-2", "category": "_L2", "capacity": "Level 2 AC", "description": "80A Dual Commercial L2 Charger (18' Cable with Modem)", "msrp": 2194.5, "ratedKw": 7.2, "connectors": 2, "connectorBasis": "description says Dual", "role": "level_2"},
  {"sku": "CTX-C80-240-1-ISO", "category": "_L2", "capacity": "Level 2 AC", "description": "80A Single Commercial L2 Charger (18' Cable with Modem)", "msrp": 2255, "ratedKw": 7.2, "connectors": 1, "connectorBasis": "description says Single", "role": "level_2"},
  {"sku": "CTX-C40-240-2-ISO", "category": "_L2", "capacity": "Level 2 AC", "description": "40A Dual Commercial L2 Charger (18' Cable with Modem)", "msrp": 2530, "ratedKw": 7.2, "connectors": 2, "connectorBasis": "description says Dual", "role": "level_2"},
  {"sku": "CTX-C80-240-2-ISO", "category": "_L2", "capacity": "Level 2 AC", "description": "80A Dual Commercial L2 Charger (18' Cable with Modem)", "msrp": 2805, "ratedKw": 7.2, "connectors": 2, "connectorBasis": "description says Dual", "role": "level_2"},
  {"sku": "TP5-30-480-1", "category": "_kW30", "capacity": "30 kW DC", "description": "Gen2 30kW DCFC Wall Mount - 100 Amps / 1000VDC with CCS1 (~16ft)", "msrp": 13750, "ratedKw": 30, "connectors": 1, "connectorBasis": "connectors named in the description", "role": "all_in_one"},
  {"sku": "TP5-30-480-3", "category": "_kW30", "capacity": "30 kW DC", "description": "Gen 2Gen 30kW DCFC Wall Mount - 200 Amps / 1000VDC with NACS (~16ft)", "msrp": 13750, "ratedKw": 30, "connectors": 1, "connectorBasis": "connectors named in the description", "role": "all_in_one"},
  {"sku": "TP5-60-480-1", "category": "_kW60", "capacity": "60 kW DC", "description": "60kW DCFC - 200 Amps / 1000VDC with CCS1 & NACS(~16ft) ; 4G Modem", "msrp": 28500, "ratedKw": 60, "connectors": 2, "connectorBasis": "connectors named in the description", "role": "all_in_one"},
  {"sku": "TP5-60-480-2", "category": "_kW60", "capacity": "60 kW DC", "description": "60kW DCFC - 200 Amps / 1000VDC with CCS1 & CCS1(~16ft) ; 4G Modem", "msrp": 28500, "ratedKw": 60, "connectors": 2, "connectorBasis": "connectors named in the description", "role": "all_in_one"},
  {"sku": "TP5-60-480-3", "category": "_kW60", "capacity": "60 kW DC", "description": "60kW DCFC - 200 Amps / 1000VDC with CCS1 & NACS(~16ft) ; 4G Modem", "msrp": 28500, "ratedKw": 60, "connectors": 2, "connectorBasis": "connectors named in the description", "role": "all_in_one"},
  {"sku": "TP5-60-480-4", "category": "_kW60", "capacity": "60 kW DC", "description": "60kW DCFC - 200 Amps / 1000VDC with NACS & NACS(~16ft) ; 4G Modem", "msrp": 28500, "ratedKw": 60, "connectors": 2, "connectorBasis": "connectors named in the description", "role": "all_in_one"},
  {"sku": "CTX-AiO-60-2-200", "category": "_kW60", "capacity": "60 kW DC", "description": "Gen 2 60kW DCFC - 200 Amps / 1000VDC with CCS1 & CCS1(~16ft) ; 4G Modem", "msrp": 31350, "ratedKw": 60, "connectors": 2, "connectorBasis": "connectors named in the description", "role": "all_in_one"},
  {"sku": "CTX-AiO-60-3-200", "category": "_kW60", "capacity": "60 kW DC", "description": "Gen 2 60kW DCFC - 200 Amps / 1000VDC with CCS1 & NACS(~16ft) ; 4G Modem", "msrp": 31350, "ratedKw": 60, "connectors": 2, "connectorBasis": "connectors named in the description", "role": "all_in_one"},
  {"sku": "CTX-AiO-60-4-200", "category": "_kW60", "capacity": "60 kW DC", "description": "Gen 2 60kW DCFC - 200 Amps / 1000VDC with NACS & NACS(~16ft) ; 4G Modem", "msrp": 31350, "ratedKw": 60, "connectors": 2, "connectorBasis": "connectors named in the description", "role": "all_in_one"},
  {"sku": "TP5-120-480-1", "category": "_kW120", "capacity": "120 kW DC", "description": "120kW DCFC All In One Charger - 200 Amps / 1000VDC with CCS1 & NACS(~16ft) ; Can charge 2 cars simultaneously with 60kW each ; 4G Modem", "msrp": 54000, "ratedKw": 120, "connectors": 2, "connectorBasis": "connectors named in the description", "role": "all_in_one"},
  {"sku": "TP5-120-480-2", "category": "_kW120", "capacity": "120 kW DC", "description": "120kW DCFC All In One Charger - 200 Amps / 1000VDC with CCS1 & CCS1(~16ft); Can charge 2 cars simultaneously with 60kW each ; 4G Modem", "msrp": 54000, "ratedKw": 120, "connectors": 2, "connectorBasis": "connectors named in the description", "role": "all_in_one"},
  {"sku": "TP5-120-480-2-300", "category": "_kW120", "capacity": "120 kW DC", "description": "120kW DCFC All In One Charger - 350A Cable / 1000VDC with CCS1 & CCS1(~16ft); Can charge 2 cars simultaneously with 60kW each ; 4G Modem", "msrp": 54000, "ratedKw": 120, "connectors": 2, "connectorBasis": "connectors named in the description", "role": "all_in_one"},
  {"sku": "TP5-120-480-3-300", "category": "_kW120", "capacity": "120 kW DC", "description": "120kW DCFC All In One Charger - 1000VDC, Cables: 350A CCS1 & 400A NACS (~16ft); Can charge 2 cars simultaneously with 60kW each ; 4G Modem", "msrp": 54000, "ratedKw": 120, "connectors": 2, "connectorBasis": "manual — description does not state the count", "role": "all_in_one"},
  {"sku": "CTX-AiO-120-2-350", "category": "_kW120", "capacity": "120 kW DC", "description": "Gen3 120kW CCS1 350A + CCS1 350A ; Cable Management + CC", "msrp": 59400, "ratedKw": 120, "connectors": 2, "connectorBasis": "connectors named in the description", "role": "all_in_one"},
  {"sku": "CTX-AiO-120-3-350", "category": "_kW120", "capacity": "120 kW DC", "description": "Gen3 120kW CCS1 350A + NACS 350A   ; Cable Management + CC", "msrp": 59400, "ratedKw": 120, "connectors": 2, "connectorBasis": "connectors named in the description", "role": "all_in_one"},
  {"sku": "CTX-AiO-120-4-350", "category": "_kW120", "capacity": "120 kW DC", "description": "Gen3 120kW NACS 350A + NACS 350A  ; Cable Management + CC", "msrp": 59400, "ratedKw": 120, "connectors": 2, "connectorBasis": "connectors named in the description", "role": "all_in_one"},
  {"sku": "CTX-AiO-120-5-350", "category": "_kW120", "capacity": "120 kW DC", "description": "Gen3 120kW Single CCS1 350A  ; Cable Management + CC", "msrp": 59400, "ratedKw": 120, "connectors": 1, "connectorBasis": "description says Single", "role": "all_in_one"},
  {"sku": "CTX-AiO-120-6-350", "category": "_kW120", "capacity": "120 kW DC", "description": "Gen3 120kW Single NACS 350A  ; Cable Management + CC", "msrp": 59400, "ratedKw": 120, "connectors": 1, "connectorBasis": "description says Single", "role": "all_in_one"},
  {"sku": "TP5-160-480-1", "category": "_kW160", "capacity": "160 kW DC", "description": "160kW DCFC All In One Charger - 200 Amps / 1000VDC with CCS1 & NACS(~16ft); It can dispense 200A on single connector and can charge 2 cars simultaneously with 80kW eac", "msrp": 57000, "ratedKw": 160, "connectors": 1, "connectorBasis": "description says Single", "role": "all_in_one"},
  {"sku": "TP5-160-480-2", "category": "_kW160", "capacity": "160 kW DC", "description": "160kW DCFC All In One Charger - 200 Amps / 1000VDC with CCS1 & CCS1(~16ft); It can dispense 200A on single connector and can charge 2 cars simultaneously with 80kW each ;", "msrp": 57000, "ratedKw": 160, "connectors": 1, "connectorBasis": "description says Single", "role": "all_in_one"},
  {"sku": "TP5-160-480-3", "category": "_kW160", "capacity": "160 kW DC", "description": "160kW DCFC All In One Charger - 200 Amps / 1000VDC with CCS1 & NACS (~16ft); It can dispense 200A on single connector and can charge 2 cars simultaneously with 80kW each", "msrp": 57000, "ratedKw": 160, "connectors": 1, "connectorBasis": "description says Single", "role": "all_in_one"},
  {"sku": "TP5-160-480-2-300", "category": "_kW160", "capacity": "160 kW DC", "description": "160kW DCFC All In One Charger - 350A Cable / 1000VDC with CCS1 & CCS1(~16ft); Can charge 2 cars simultaneously with 80kW each ; 4G Modem", "msrp": 57000, "ratedKw": 160, "connectors": 2, "connectorBasis": "connectors named in the description", "role": "all_in_one"},
  {"sku": "HPC-160-480-1", "category": "_kW160", "capacity": "160 kW DC", "description": "160kW HPC All In One Charger - 400 Amps / 1000VDC with Liquid Cooled Connector for CCS1(~14ft) & NACS(~16ft) ; It can deliver 400A on the CCS coonnector. Can charge 2", "msrp": 68000, "ratedKw": 160, "connectors": 2, "connectorBasis": "connectors named in the description", "role": "all_in_one"},
  {"sku": "HPC-160-480-2", "category": "_kW160", "capacity": "160 kW DC", "description": "160kW HPC All In One Charger - 400 Amps / 1000VDC with Liquid Cooled Connector for CCS1(~14ft) & NACS(~16ft) ; It can deliver 400A on the CCS coonnector. Also can char", "msrp": 70000, "ratedKw": 160, "connectors": 2, "connectorBasis": "connectors named in the description", "role": "all_in_one"},
  {"sku": "CTX-AiO-160-2-350", "category": "_kW160", "capacity": "160 kW DC", "description": "Gen3 160kW CCS1 350A + CCS1 350A ; Cable Management + CC", "msrp": 68200, "ratedKw": 160, "connectors": 2, "connectorBasis": "connectors named in the description", "role": "all_in_one"},
  {"sku": "CTX-AiO-160-3-350", "category": "_kW160", "capacity": "160 kW DC", "description": "Gen3 160kW CCS1 350A + NACS 350A   ; Cable Management + CC", "msrp": 68200, "ratedKw": 160, "connectors": 2, "connectorBasis": "connectors named in the description", "role": "all_in_one"},
  {"sku": "CTX-AiO-160-4-350", "category": "_kW160", "capacity": "160 kW DC", "description": "Gen3 160kW NACS 350A + NACS 350A  ; Cable Management + CC", "msrp": 68200, "ratedKw": 160, "connectors": 2, "connectorBasis": "connectors named in the description", "role": "all_in_one"},
  {"sku": "CTX-AiO-160-5-350", "category": "_kW160", "capacity": "160 kW DC", "description": "Gen3 160kW Single CCS1 350A  ; Cable Management + CC", "msrp": 68200, "ratedKw": 160, "connectors": 1, "connectorBasis": "description says Single", "role": "all_in_one"},
  {"sku": "CTX-AiO-160-6-350", "category": "_kW160", "capacity": "160 kW DC", "description": "Gen3 160kW Single NACS 350A  ; Cable Management + CC", "msrp": 68200, "ratedKw": 160, "connectors": 1, "connectorBasis": "description says Single", "role": "all_in_one"},
  {"sku": "TP5-180-480-1", "category": "_kW180", "capacity": "180 kW DC", "description": "180kW DCFC All In One Charger - 200 Amps / 1000VDC with CCS1 & NACS(~16ft); Can charge 2 cars simultaneously with 90kW each or 120kW on CCS1 and 60kW on NACS; 4G Mo", "msrp": 62000, "ratedKw": 180, "connectors": 2, "connectorBasis": "connectors named in the description", "role": "all_in_one"},
  {"sku": "TP5-180-480-2", "category": "_kW180", "capacity": "180 kW DC", "description": "180kW DCFC All In One Charger - 200 Amps / 1000VDC with CCS1 & CCS1(~16ft); Can charge 2 cars simultaneously with 90kW each ; 4G Modem", "msrp": 62000, "ratedKw": 180, "connectors": 2, "connectorBasis": "connectors named in the description", "role": "all_in_one"},
  {"sku": "TP5-180-480-2-300", "category": "_kW180", "capacity": "180 kW DC", "description": "180kW DCFC All In One Charger - 350A Cable / 1000VDC with CCS1 & CCS1(~16ft); Can charge 2 cars simultaneously with 90kW each ; 4G Modem", "msrp": 62000, "ratedKw": 180, "connectors": 2, "connectorBasis": "connectors named in the description", "role": "all_in_one"},
  {"sku": "TP5-180-480-3-300", "category": "_kW180", "capacity": "180 kW DC", "description": "180kW DCFC All In One Charger - 1000VDC, Cables: 350A CCS1 & 400A NACS (~16ft); Can charge 2 cars simultaneously with 90kW each ; 4G Modem", "msrp": 62000, "ratedKw": 180, "connectors": 2, "connectorBasis": "manual — description does not state the count", "role": "all_in_one"},
  {"sku": "TP5-180-480-2-300-CL20", "category": "_kW180", "capacity": "180 kW DC", "description": "180kW DCFC All In One Charger - 350A Cable / 1000VDC with CCS1 & CCS1(~20ft); Can charge 2 cars simultaneously with 90kW each ; 4G Modem", "msrp": 62000, "ratedKw": 180, "connectors": 2, "connectorBasis": "connectors named in the description", "role": "all_in_one"},
  {"sku": "TP5-240-480-2-300", "category": "_kW240", "capacity": "240 kW DC", "description": "240kW DCFC All In One Charger - 350A Cable / 1000VDC Dual CCS1 ; Can charge 2 cars simultaneously with 120kW each ; 4G Modem", "msrp": 80000, "ratedKw": 240, "connectors": 2, "connectorBasis": "description says Dual", "role": "all_in_one"},
  {"sku": "TP5-240-480-2-400", "category": "_kW240", "capacity": "240 kW DC", "description": "240kW DCFC All In One Charger - 1000VDC, Cables: 350A CCS1 & 400A NACS; Can charge 2 cars simultaneously with 120kW each ; 4G Modem", "msrp": 80000, "ratedKw": 240, "connectors": 2, "connectorBasis": "manual — description does not state the count", "role": "all_in_one"},
  {"sku": "HPC-240-480-1", "category": "_kW240", "capacity": "240 kW DC", "description": "240kW HPC All In One Charger - 500 Amps / 1000VDC with Liquid Cooled Connector for CCS1 & NACS(~14ft) ; Can deliver 500A on CCS coonnector. Can charge 2 cars simultane", "msrp": 98000, "ratedKw": 240, "connectors": 2, "connectorBasis": "connectors named in the description", "role": "all_in_one"},
  {"sku": "HPC-240-480-2", "category": "_kW240", "capacity": "240 kW DC", "description": "240kW HPC All In One Charger - 500 Amps / 1000VDC with Liquid Cooled Connector for Dual CCS1 ; Can deliver 450A on one CCS coonnector and 250A on each connector if used s", "msrp": 98000, "ratedKw": 240, "connectors": 2, "connectorBasis": "description says Dual", "role": "all_in_one"},
  {"sku": "CTX-AiO-240-2-300", "category": "_kW240", "capacity": "240 kW DC", "description": "Gen3 240kW CCS1 350A + CCS1 350A; Cable Management + CC", "msrp": 88000, "ratedKw": 240, "connectors": 2, "connectorBasis": "connectors named in the description", "role": "all_in_one"},
  {"sku": "CTX-AiO-240-3-300", "category": "_kW240", "capacity": "240 kW DC", "description": "Gen3 240kW CCS1 350A + NACS 350A; Cable Management + CC", "msrp": 88000, "ratedKw": 240, "connectors": 2, "connectorBasis": "connectors named in the description", "role": "all_in_one"},
  {"sku": "CTX-AiO-240-4-300", "category": "_kW240", "capacity": "240 kW DC", "description": "Gen3 240kW NACS 350A + NACS 350A; Cable Management + CC", "msrp": 88000, "ratedKw": 240, "connectors": 2, "connectorBasis": "connectors named in the description", "role": "all_in_one"},
  {"sku": "CTX-AiO-240-5-300", "category": "_kW240", "capacity": "240 kW DC", "description": "Gen3 240kW Single CCS1 350A; Cable Management + CC", "msrp": 88000, "ratedKw": 240, "connectors": 1, "connectorBasis": "description says Single", "role": "all_in_one"},
  {"sku": "TP5-360-480-1-300", "category": "_kW360", "capacity": "360 kW DC", "description": "360kW DCFC All In One Charger - 1000VDC, Cables: 350A CCS1 & NACS ;  Can charge 2 cars simultaneously with 180kW each ; 4G Modem", "msrp": 99000, "ratedKw": 360, "connectors": 2, "connectorBasis": "manual — description does not state the count", "role": "all_in_one"},
  {"sku": "TP5-360-480-2-300", "category": "_kW360", "capacity": "360 kW DC", "description": "360kW DCFC All In One Charger - 350A Cable / 1000VDC Dual CCS1 ;  Can charge 2 cars simultaneously with 180kW each ; 4G Modem", "msrp": 99000, "ratedKw": 360, "connectors": 2, "connectorBasis": "description says Dual", "role": "all_in_one"},
  {"sku": "TP5-360-480-3-300", "category": "_kW360", "capacity": "360 kW DC", "description": "360kW DCFC All In One Charger - 1000VDC, Cables: 350A CCS1 & 400A NACS ;  Can charge 2 cars simultaneously with 180kW each ; 4G Modem", "msrp": 99000, "ratedKw": 360, "connectors": 2, "connectorBasis": "manual — description does not state the count", "role": "all_in_one"},
  {"sku": "TP5-360-480-4-300", "category": "_kW360", "capacity": "360 kW DC", "description": "360kW DCFC All In One Charger - 1000VDC, Cables: 400A NACS / 400A NACS ;  Can charge 2 cars simultaneously with 180kW each ; 4G Modem", "msrp": 99000, "ratedKw": 360, "connectors": 2, "connectorBasis": "manual — description does not state the count", "role": "all_in_one"},
  {"sku": "HPC-360-480-1", "category": "_kW360", "capacity": "360 kW DC", "description": "360kW HPC All In One Charger - 500 Amps / 1000VDC with Liquid Cooled Connector for CCS1 & NACS(~14ft) ; Can deliver 500A on CCS coonnector. Can charge 2 cars simultane", "msrp": 110000, "ratedKw": 360, "connectors": 2, "connectorBasis": "connectors named in the description", "role": "all_in_one"},
  {"sku": "HPC-360-480-2", "category": "_kW360", "capacity": "360 kW DC", "description": "360kW HPC All In One Charger - 500 Amps / 1000VDC with Liquid Cooled Connector for Dual CCS1 ; Can deliver 500A on one CCS coonnector and 400A on each connector if used s", "msrp": 110000, "ratedKw": 360, "connectors": 2, "connectorBasis": "description says Dual", "role": "all_in_one"},
  {"sku": "HPC-360-480-3", "category": "_kW360", "capacity": "360 kW DC", "description": "360kW HPC All In One Charger - 500 Amps / 1000VDC with Liquid Cooled Connector for CCS1 & NACS ; Can deliver 500A on CCS coonnector. Can charge 2 cars simultaneously; 4G", "msrp": 110000, "ratedKw": 360, "connectors": 2, "connectorBasis": "connectors named in the description", "role": "all_in_one"},
  {"sku": "HPC-360-480-4", "category": "_kW360", "capacity": "360 kW DC", "description": "360kW HPC All In One Charger - 500 Amps / 1000VDC with Liquid Cooled Connector for NACS / NACS ; Can deliver 500A on CCS coonnector. Can charge 2 cars simultaneously; 4G", "msrp": 110000, "ratedKw": 360, "connectors": 2, "connectorBasis": "connectors named in the description", "role": "all_in_one"},
  {"sku": "CTX-DSPB-360", "category": "_Distributed_System", "capacity": "Distributed system", "description": "360kW Tower", "msrp": 81400, "ratedKw": 360, "connectors": 0, "connectorBasis": "distributed system — the architecture table holds this", "role": "power_cabinet"},
  {"sku": "CTX-DSPB-480", "category": "_Distributed_System", "capacity": "Distributed system", "description": "480kW Tower", "msrp": 90200, "ratedKw": 480, "connectors": 0, "connectorBasis": "distributed system — the architecture table holds this", "role": "power_cabinet"},
  {"sku": "CTX-DSPB-1280", "category": "_Distributed_System", "capacity": "Distributed system", "description": "1,280kW Tower", "msrp": 225000, "ratedKw": 1280, "connectors": 0, "connectorBasis": "distributed system — the architecture table holds this", "role": "power_cabinet"},
  {"sku": "CTX-DST-2-300", "category": "_Distributed_System", "capacity": "Distributed system", "description": "Dispenser 300/300", "msrp": 35200, "ratedKw": 0, "connectors": 0, "connectorBasis": "distributed system — the architecture table holds this", "role": "dispenser"},
  {"sku": "CTX-DST-HPC-2-500/300", "category": "_Distributed_System", "capacity": "Distributed system", "description": "Dispenser 500/300", "msrp": 49500, "ratedKw": 0, "connectors": 0, "connectorBasis": "distributed system — the architecture table holds this", "role": "dispenser"},
  {"sku": "TP5-60-480-2-BAA", "category": "_Buy_America", "capacity": "60 kW DC", "description": "Buy America NEVI Compliant, Assembled in CA, USA 60kW DCFC - 140 Amps / 1000VDC with CCS1 & CCS1(~16ft) ; 4G Modem", "msrp": 68200, "ratedKw": 60, "connectors": 2, "connectorBasis": "connectors named in the description", "role": "all_in_one"},
  {"sku": "TP5-60-480-3-BAA", "category": "_Buy_America", "capacity": "60 kW DC", "description": "Buy America NEVI Compliant, Assembled in CA, USA 60kW DCFC - 140 Amps / 1000VDC with CCS1 & NACS ; 4G Modem", "msrp": 68200, "ratedKw": 60, "connectors": 2, "connectorBasis": "connectors named in the description", "role": "all_in_one"},
  {"sku": "TP5-60-480-4-BAA", "category": "_Buy_America", "capacity": "60 kW DC", "description": "Buy America NEVI Compliant, Assembled in CA, USA 60kW DCFC - 140 Amps / 1000VDC with NACS & NACS ; 4G Modem", "msrp": 68200, "ratedKw": 60, "connectors": 2, "connectorBasis": "connectors named in the description", "role": "all_in_one"},
  {"sku": "TP5-120-480-2-300-BAA", "category": "_Buy_America", "capacity": "120 kW DC", "description": "Buy America NEVI Compliant, Assembled in CA, USA 120kW DCFC All In One Charger - 350A Cable / 1000VDC with CCS1 & CCS1(~16ft); Can charge 2 cars simultaneously with 60kW", "msrp": 75900, "ratedKw": 120, "connectors": 2, "connectorBasis": "connectors named in the description", "role": "all_in_one"},
  {"sku": "TP5-120-480-3-300-BAA", "category": "_Buy_America", "capacity": "120 kW DC", "description": "Buy America NEVI Compliant, Assembled in CA, USA 120kW DCFC All In One Charger - 350A Cable / 1000VDC with CCS1 & NACS; Can charge 2 cars simultaneously with 60kW each ;", "msrp": 75900, "ratedKw": 120, "connectors": 2, "connectorBasis": "connectors named in the description", "role": "all_in_one"},
  {"sku": "TP5-120-480-4-300-BAA", "category": "_Buy_America", "capacity": "120 kW DC", "description": "Buy America NEVI Compliant, Assembled in CA, USA 120kW DCFC All In One Charger - 350A Cable / 1000VDC with NACS & NACS(~16ft); Can charge 2 cars simultaneously with 60kW", "msrp": 75900, "ratedKw": 120, "connectors": 2, "connectorBasis": "connectors named in the description", "role": "all_in_one"},
  {"sku": "TP5-180-480-2-BAA", "category": "_Buy_America", "capacity": "180 kW DC", "description": "Buy America NEVI Compliant, Assembled in CA, USA 180kW Air Cooled 350A Cable (BAA) CCS1 / CCS1 1000VDC Connector for Dual CCS1; Can deliver 350A on one CCS conector. Set", "msrp": 82500, "ratedKw": 180, "connectors": 2, "connectorBasis": "description says Dual", "role": "all_in_one"},
  {"sku": "TP5-180-480-3-BAA", "category": "_Buy_America", "capacity": "180 kW DC", "description": "Buy America NEVI Compliant, Assembled in CA, USA 180kW Air Cooled 350A Cable (BAA)  CCS1 / NACS 1000VDC Connector for Dual CCS1; Can deliver 350A on one CCS conector. Set", "msrp": 82500, "ratedKw": 180, "connectors": 2, "connectorBasis": "description says Dual", "role": "all_in_one"},
  {"sku": "TP5-180-480-4-BAA", "category": "_Buy_America", "capacity": "180 kW DC", "description": "Buy America NEVI Compliant, Assembled in CA, USA 180kW Air Cooled 350A Cable (BAA) NACS / NACS 1000VDC Connector for Dual CCS1; Can deliver 350A on one CCS conector. Set", "msrp": 82500, "ratedKw": 180, "connectors": 2, "connectorBasis": "description says Dual", "role": "all_in_one"},
  {"sku": "HPC-180-480-2-BAA", "category": "_Buy_America", "capacity": "180 kW DC", "description": "Buy America NEVI Compliant, Assembled in CA, USA 180kW Liquid Cooled (BAA) Dual CCS1 500 Amps / 1000VDC with Liquid Cooled Connector for Dual CCS1 ; Can deliver 450A on o", "msrp": 82500, "ratedKw": 180, "connectors": 2, "connectorBasis": "description says Dual", "role": "all_in_one"},
  {"sku": "HPC-180-480-3-BAA", "category": "_Buy_America", "capacity": "180 kW DC", "description": "Buy America NEVI Compliant, Assembled in CA, USA 180kW Liquid Cooled (BAA) CCS1 / NACS 1000VDC with Liquid Cooled Connector for Dual CCS1 ; Can deliver 450A on one CCS co", "msrp": 82500, "ratedKw": 180, "connectors": 2, "connectorBasis": "description says Dual", "role": "all_in_one"},
  {"sku": "HPC-180-480-4-BAA", "category": "_Buy_America", "capacity": "180 kW DC", "description": "Buy America NEVI Compliant, Assembled in CA, USA 180kW Liquid Cooled (BAA) NACS /NACS 1000VDC with Liquid Cooled Connector for Dual CCS1 ; Can deliver 450A on one CCS con", "msrp": 82500, "ratedKw": 180, "connectors": 2, "connectorBasis": "description says Dual", "role": "all_in_one"},
  {"sku": "TP5-360-480-2-BAA", "category": "_Buy_America", "capacity": "360 kW DC", "description": "Buy America NEVI Compliant 360kW Air Cooled 350A Cable (BAA) Dual CCS1 / 1000VDC Connector for Dual CCS1 ; Can deliver 350A on one CCS connector and 350A on each connecto", "msrp": 138600, "ratedKw": 360, "connectors": 2, "connectorBasis": "description says Dual", "role": "all_in_one"},
  {"sku": "TP5-360-480-3-BAA", "category": "_Buy_America", "capacity": "360 kW DC", "description": "Buy America NEVI Compliant 360kW Air Cooled 350A Cable (BAA) Dual CCS1 / 1000VDC Connector for CCS1/NACS ; Can deliver 350A on one CCS connector and 350A on each connecto", "msrp": 138600, "ratedKw": 360, "connectors": 2, "connectorBasis": "description says Dual", "role": "all_in_one"},
  {"sku": "TP5-360-480-4-BAA", "category": "_Buy_America", "capacity": "360 kW DC", "description": "Buy America NEVI Compliant 360kW Air Cooled 350A Cable (BAA) Dual CCS1 / 1000VDC Connector for NACS/NACS ; Can deliver 350A on one CCS connector and 350A on each connecto", "msrp": 138600, "ratedKw": 360, "connectors": 2, "connectorBasis": "description says Dual", "role": "all_in_one"},
  {"sku": "HPC-360-480-2-BAA", "category": "_Buy_America", "capacity": "360 kW DC", "description": "Buy America NEVI Compliant 360kW Liquid Cooled (BAA) 500 Amps / 1000VDC with Liquid Cooled Connector for Dual CCS1 ; Can deliver 500A on one CCS connector and 400A on eac", "msrp": 137500, "ratedKw": 360, "connectors": 2, "connectorBasis": "description says Dual", "role": "all_in_one"},
  {"sku": "HPC-360-480-3-BAA", "category": "_Buy_America", "capacity": "360 kW DC", "description": "Buy America NEVI Compliant 360kW Liquid Cooled (BAA) 500 Amps / 1000VDC with Liquid Cooled Connector for CCS1/NACS ; Can deliver 500A on one CCS connector and 400A on eac", "msrp": 137500, "ratedKw": 360, "connectors": 2, "connectorBasis": "connectors named in the description", "role": "all_in_one"},
  {"sku": "HPC-360-480-4-BAA", "category": "_Buy_America", "capacity": "360 kW DC", "description": "Buy America NEVI Compliant 360kW Liquid Cooled (BAA) 500 Amps / 1000VDC with Liquid Cooled Connector for NACS/NACS ; Can deliver 500A on one CCS connector and 400A on eac", "msrp": 137500, "ratedKw": 360, "connectors": 2, "connectorBasis": "connectors named in the description", "role": "all_in_one"},
  {"sku": "CTX-V2G-20-480-1", "category": "_V2G", "capacity": "V2G", "description": "20kW V2G Charger", "msrp": 16700, "ratedKw": 0, "connectors": 1, "connectorBasis": "manual — description does not state the count", "role": "all_in_one"},
  {"sku": "CTX-V2G-30-480-1", "category": "_V2G", "capacity": "V2G", "description": "30kW V2G Charger", "msrp": 23800, "ratedKw": 0, "connectors": 1, "connectorBasis": "manual — description does not state the count", "role": "all_in_one"},
  {"sku": "CTX-V2G-40-480-1", "category": "_V2G", "capacity": "V2G", "description": "40kW V2G Charger", "msrp": 35900, "ratedKw": 0, "connectors": 1, "connectorBasis": "manual — description does not state the count", "role": "all_in_one"},
  {"sku": "CTX-V2G-60-480-1", "category": "_V2G", "capacity": "V2G", "description": "60kW V2G Charger", "msrp": 50000, "ratedKw": 0, "connectors": 1, "connectorBasis": "manual — description does not state the count", "role": "all_in_one"},
  {"sku": "CTX-FLUXPED", "category": "_L2_Accessories", "capacity": "Accessory", "description": "Single Post (no Retraction)", "msrp": 412.5, "ratedKw": 0, "connectors": 0, "connectorBasis": "accessory — not a charging position", "role": "accessory"},
  {"sku": "CTX-FLUXWAL-CMS-1", "category": "_L2_Accessories", "capacity": "Accessory", "description": "Single Retractor (Wall)", "msrp": 275, "ratedKw": 0, "connectors": 0, "connectorBasis": "accessory — not a charging position", "role": "accessory"},
  {"sku": "CTX-FLUXPED-CMS-1", "category": "_L2_Accessories", "capacity": "Accessory", "description": "Single Retractor post", "msrp": 412.5, "ratedKw": 0, "connectors": 0, "connectorBasis": "accessory — not a charging position", "role": "accessory"},
  {"sku": "CTX-FLUXPED-CMS-2", "category": "_L2_Accessories", "capacity": "Accessory", "description": "Dual Retractor (Post)", "msrp": 632.5, "ratedKw": 0, "connectors": 0, "connectorBasis": "accessory — not a charging position", "role": "accessory"},
  {"sku": "CTX-FLUXPED-SBS", "category": "_L2_Accessories", "capacity": "Accessory", "description": "Side By Side Bracket", "msrp": 137.5, "ratedKw": 0, "connectors": 0, "connectorBasis": "accessory — not a charging position", "role": "accessory"},
];

export interface CapacityRow {
  capacity: string;
  ratedKw: number;
  perPort: number;
}

export const CAPACITIES: CapacityRow[] = [
  {"capacity": "Level 2 AC", "ratedKw": 7.2, "perPort": 1},
  {"capacity": "30 kW DC", "ratedKw": 30, "perPort": 0},
  {"capacity": "60 kW DC", "ratedKw": 60, "perPort": 0},
  {"capacity": "120 kW DC", "ratedKw": 120, "perPort": 0},
  {"capacity": "160 kW DC", "ratedKw": 160, "perPort": 0},
  {"capacity": "180 kW DC", "ratedKw": 180, "perPort": 0},
  {"capacity": "240 kW DC", "ratedKw": 240, "perPort": 0},
  {"capacity": "360 kW DC", "ratedKw": 360, "perPort": 0},
  {"capacity": "V2G", "ratedKw": 0, "perPort": 0},
  {"capacity": "Distributed system", "ratedKw": 0, "perPort": 0},
  {"capacity": "Accessory", "ratedKw": 0, "perPort": 0},
];

/** Per cabinet per year. Service is sold only against a warranty in force. */
export interface ServiceRate {
  class: string;
  yearlyWarranty: number;
  inWarrantyService: number;
  /** Yearly warranty + in-warranty service — the rate from year 3 on. */
  warrantyPlusServiceYr3: number;
  outOfWarrantyService: number | "NOT OFFERED";
  includedWarranty: string;
}

export const SERVICE_RATES: ServiceRate[] = [
  {"class": "AC Charger - 7.2 kW UP80J-PMP Single", "yearlyWarranty": 416.0, "inWarrantyService": 320.11, "warrantyPlusServiceYr3": 736.11, "outOfWarrantyService": "NOT OFFERED", "includedWarranty": "1 year, parts only"},
  {"class": "AC Charger - 2 x 7.2 kW UP160J-PMP Dual", "yearlyWarranty": 416.0, "inWarrantyService": 320.11, "warrantyPlusServiceYr3": 736.11, "outOfWarrantyService": "NOT OFFERED", "includedWarranty": "1 year, parts only"},
  {"class": "AC Charger - 7.2 kW UP80J-WMP Single", "yearlyWarranty": 416.0, "inWarrantyService": 320.11, "warrantyPlusServiceYr3": 736.11, "outOfWarrantyService": "NOT OFFERED", "includedWarranty": "1 year, parts only"},
  {"class": "AC Charger - 2 x 7.2 kW UP160J-WMP Dual", "yearlyWarranty": 416.0, "inWarrantyService": 320.11, "warrantyPlusServiceYr3": 736.11, "outOfWarrantyService": "NOT OFFERED", "includedWarranty": "1 year, parts only"},
  {"class": "DC-60kW CCS1 + NACS", "yearlyWarranty": 962.84, "inWarrantyService": 1476.36, "warrantyPlusServiceYr3": 2439.2, "outOfWarrantyService": "NOT OFFERED", "includedWarranty": "2 years, parts only"},
  {"class": "DC-120kW CCS1 + NACS", "yearlyWarranty": 1196.91, "inWarrantyService": 1616.76, "warrantyPlusServiceYr3": 2813.67, "outOfWarrantyService": "NOT OFFERED", "includedWarranty": "2 years, parts only"},
  {"class": "DC-160kW CCS1 + NACS", "yearlyWarranty": 1428.57, "inWarrantyService": 1879.2, "warrantyPlusServiceYr3": 3307.77, "outOfWarrantyService": "NOT OFFERED", "includedWarranty": "2 years, parts only"},
  {"class": "DC-180KW", "yearlyWarranty": 1856.84, "inWarrantyService": 2708.64, "warrantyPlusServiceYr3": 4565.48, "outOfWarrantyService": "NOT OFFERED", "includedWarranty": "2 years, parts only"},
  {"class": "DC-240KW", "yearlyWarranty": 2708.64, "inWarrantyService": 6478.75, "warrantyPlusServiceYr3": 9187.39, "outOfWarrantyService": "NOT OFFERED", "includedWarranty": "2 years, parts only"},
  {"class": "DC-360kW CCS1 + CCS1", "yearlyWarranty": 4051.08, "inWarrantyService": 4898.88, "warrantyPlusServiceYr3": 8949.96, "outOfWarrantyService": "NOT OFFERED", "includedWarranty": "2 years, parts only"},
  {"class": "CTX-DSPB-360", "yearlyWarranty": 5063.85, "inWarrantyService": 6123.6, "warrantyPlusServiceYr3": 11187.45, "outOfWarrantyService": "NOT OFFERED", "includedWarranty": "2 years, parts only"},
  {"class": "CTX-DSPB-480", "yearlyWarranty": 6583.01, "inWarrantyService": 7654.5, "warrantyPlusServiceYr3": 14237.51, "outOfWarrantyService": "NOT OFFERED", "includedWarranty": "2 years, parts only"},
  {"class": "CTX-DSPB-1280", "yearlyWarranty": 9874.51, "inWarrantyService": 9568.12, "warrantyPlusServiceYr3": 19442.63, "outOfWarrantyService": "NOT OFFERED", "includedWarranty": "2 years, parts only"},
  {"class": "CTX-DST-2-300/CTX-DST-HPC-2-500/300", "yearlyWarranty": 962.84, "inWarrantyService": 1476.36, "warrantyPlusServiceYr3": 2439.2, "outOfWarrantyService": "NOT OFFERED", "includedWarranty": ""},
];

/** What each distributed-system SKU is — from the Chargetronix Nexus spec sheets. */
export interface ArchitectureRow {
  sku: string;
  role: string;
  dcKw: number;
  acKw: number;
  acCircuits: number;
  acFla: number;
  dcOutputs: number;
  maxDualDispensers: number;
  source: string;
}

export const ARCHITECTURE: ArchitectureRow[] = [
  {"sku": "CTX-DSPB-360", "role": "Power cabinet — no connectors", "dcKw": 360, "acKw": 393, "acCircuits": 2, "acFla": 472.7, "dcOutputs": 6, "maxDualDispensers": 3, "source": "DERIVED — AC input, circuit count and the 3-dispenser limit extrapolated from the published 480 kW cabinet. Confirm all three with Chargetronix before sizing service."},
  {"sku": "CTX-DSPB-480", "role": "Power cabinet — no connectors", "dcKw": 480, "acKw": 524, "acCircuits": 2, "acFla": 630.3, "dcOutputs": 6, "maxDualDispensers": 3, "source": "PUBLISHED — 480 VAC +/-10%, 3P+PE, 2 input circuits at 315 A each, input power 524 kW, output 480 kW, 200-1000 VDC, 500 A per channel, 1,600 A system, up to 6 DC outputs, dynamic power sharing in 40 kW increments. Takes UP TO 3 DUAL DISPENSERS (6 connectors)."},
  {"sku": "CTX-DSPB-1280", "role": "Power cabinet — no connectors", "dcKw": 1280, "acKw": 1397.3, "acCircuits": 6, "acFla": 1680.7, "dcOutputs": 16, "maxDualDispensers": 8, "source": "PART PUBLISHED — 1,280 kW output, 480 VAC, 200-1000 VDC, 500 A per output, 4,267 A total, 16 connectors max — so UP TO 8 DUAL DISPENSERS. AC input power and circuit count are DERIVED; confirm with Chargetronix before sizing service."},
  {"sku": "CTX-DST-2-300", "role": "Dispenser — connectors only", "dcKw": 0, "acKw": 0, "acCircuits": 0, "acFla": 0, "dcOutputs": 2, "maxDualDispensers": 0, "source": "PUBLISHED — 2 connectors CCS1/NACS, 200-1000 V, up to 2 input circuits per dispenser, load sharing across 2 EVs, 5 m cable, 15 in touchscreen, 241 kg."},
  {"sku": "CTX-DST-HPC-2-500/300", "role": "Dispenser — connectors only", "dcKw": 0, "acKw": 0, "acCircuits": 0, "acFla": 0, "dcOutputs": 2, "maxDualDispensers": 0, "source": "PUBLISHED — liquid-cooled connector rated 500 A, air-cooled 200/350 A boost to 400 A."},
];

export function findSku(sku: string): PriceBookSku | undefined {
  return PRICE_BOOK.find((s) => s.sku === sku);
}
