// GENERATED by scripts/import-intake-refdata.py — do not edit by hand.
// Delivery utilities that set their own retail tariff (California and Michigan), plus the rate-schedule picker.
// Source: EVSE_Project_Intake_TEMPLATE_3.1.0.xlsx (EVSE Project Intake template 3.1.0,
// released 2026-09-03, content hash 4aecae7d4b5f25a9). Generated 2026-09-11.
// Re-run `npm run refdata` when the CEO releases a new template.


export interface UtilityRow {
  utility: string;
  /** IOU / POU / Co-op … */
  type: string;
  territory: string;
  evRateStatus: string;
  state: string;
}

export const UTILITIES: UtilityRow[] = [
  {"utility": "PG&E — Pacific Gas and Electric", "type": "IOU", "territory": "Northern & central CA, 47 counties", "evRateStatus": "EV rate: BEV-1 / BEV-2-S / BEV-2-P", "state": "California"},
  {"utility": "SCE — Southern California Edison", "type": "IOU", "territory": "Central & southern CA, 15 counties", "evRateStatus": "EV rate: TOU-EV-7 / 8 / 9", "state": "California"},
  {"utility": "SDG&E — San Diego Gas & Electric", "type": "IOU", "territory": "San Diego Co. + southern Orange Co.", "evRateStatus": "EV rate: EV-HP", "state": "California"},
  {"utility": "Liberty Utilities (CalPeco Electric)", "type": "IOU", "territory": "North Lake Tahoe & eastern Sierra", "evRateStatus": "EV rate: TOU A-1/A-2/A-3 EV", "state": "California"},
  {"utility": "Pacific Power (PacifiCorp)", "type": "IOU", "territory": "Siskiyou, Modoc, Shasta, Del Norte", "evRateStatus": "NO commercial EV rate", "state": "California"},
  {"utility": "Bear Valley Electric Service (BVES)", "type": "IOU", "territory": "Big Bear Lake, San Bernardino Co.", "evRateStatus": "EV rate: TOU-EV-2 / TOU-EV-3 (max 500 kW)", "state": "California"},
  {"utility": "LADWP — Los Angeles Dept of Water & Power", "type": "POU", "territory": "City of Los Angeles + Owens Valley", "evRateStatus": "EV rate: EVA1 / EVA2 / EVA3 (pilot)", "state": "California"},
  {"utility": "SMUD — Sacramento Municipal Utility District", "type": "POU", "territory": "Sacramento Co. + part of Placer Co.", "evRateStatus": "EV rate: EV_SR subscription", "state": "California"},
  {"utility": "IID — Imperial Irrigation District", "type": "POU", "territory": "Imperial Co. + eastern Coachella Valley", "evRateStatus": "NO EV rate", "state": "California"},
  {"utility": "MID — Modesto Irrigation District", "type": "POU", "territory": "Modesto & Stanislaus Co.", "evRateStatus": "NO commercial EV rate", "state": "California"},
  {"utility": "Anaheim Public Utilities", "type": "POU", "territory": "City of Anaheim, Orange Co.", "evRateStatus": "EV rate D-EV-2 CLOSED to new customers", "state": "California"},
  {"utility": "Riverside Public Utilities", "type": "POU", "territory": "City of Riverside", "evRateStatus": "EV rate SMEVC capped below 150 kW", "state": "California"},
  {"utility": "TID — Turlock Irrigation District", "type": "POU", "territory": "Turlock; Stanislaus, Merced, Tuolumne", "evRateStatus": "NO EV rate", "state": "California"},
  {"utility": "Glendale Water and Power", "type": "POU", "territory": "City of Glendale, LA Co.", "evRateStatus": "NO commercial EV rate", "state": "California"},
  {"utility": "Roseville Electric Utility", "type": "POU", "territory": "City of Roseville, Placer Co.", "evRateStatus": "NO commercial EV rate", "state": "California"},
  {"utility": "Pasadena Water and Power", "type": "POU", "territory": "City of Pasadena, LA Co.", "evRateStatus": "NO commercial EV rate", "state": "California"},
  {"utility": "Silicon Valley Power (Santa Clara)", "type": "POU", "territory": "City of Santa Clara", "evRateStatus": "NO EV rate — by policy", "state": "California"},
  {"utility": "Burbank Water and Power", "type": "POU", "territory": "City of Burbank, LA Co.", "evRateStatus": "NO commercial EV rate", "state": "California"},
  {"utility": "Redding Electric Utility", "type": "POU", "territory": "City of Redding, Shasta Co.", "evRateStatus": "Not researched", "state": "California"},
  {"utility": "Alameda Municipal Power", "type": "POU", "territory": "City of Alameda", "evRateStatus": "NO commercial EV rate", "state": "California"},
  {"utility": "City of Palo Alto Utilities", "type": "POU", "territory": "City of Palo Alto", "evRateStatus": "NO commercial EV rate", "state": "California"},
  {"utility": "Lodi Electric Utility", "type": "POU", "territory": "City of Lodi, San Joaquin Co.", "evRateStatus": "Not researched", "state": "California"},
  {"utility": "Colton Public Utilities", "type": "POU", "territory": "City of Colton, San Bernardino Co.", "evRateStatus": "EV rate page exists — obtain tariff", "state": "California"},
  {"utility": "Azusa Light & Water", "type": "POU", "territory": "City of Azusa, LA Co.", "evRateStatus": "NO commercial EV rate", "state": "California"},
  {"utility": "Lompoc Electric Division", "type": "POU", "territory": "City of Lompoc, Santa Barbara Co.", "evRateStatus": "Not researched", "state": "California"},
  {"utility": "Truckee Donner PUD", "type": "POU", "territory": "Truckee & Donner, Nevada/Placer Co.", "evRateStatus": "Not researched", "state": "California"},
  {"utility": "Banning Electric Utility", "type": "POU", "territory": "City of Banning, Riverside Co.", "evRateStatus": "Not researched", "state": "California"},
  {"utility": "Merced Irrigation District", "type": "POU", "territory": "Merced County", "evRateStatus": "Not researched", "state": "California"},
  {"utility": "LMUD — Lassen Municipal Utility District", "type": "POU", "territory": "Susanville & Lassen Co.", "evRateStatus": "Not researched", "state": "California"},
  {"utility": "Ukiah Electric Utility", "type": "POU", "territory": "City of Ukiah, Mendocino Co.", "evRateStatus": "Not researched", "state": "California"},
  {"utility": "Trinity Public Utilities District", "type": "POU", "territory": "Trinity County", "evRateStatus": "Not researched", "state": "California"},
  {"utility": "Healdsburg Electric Department", "type": "POU", "territory": "City of Healdsburg, Sonoma Co.", "evRateStatus": "Not researched", "state": "California"},
  {"utility": "Shasta Lake Electric Utility", "type": "POU", "territory": "City of Shasta Lake, Shasta Co.", "evRateStatus": "Not researched", "state": "California"},
  {"utility": "Rancho Cucamonga Municipal Utility", "type": "POU", "territory": "PARTIAL — newer development only; SCE serves the rest", "evRateStatus": "Not researched", "state": "California"},
  {"utility": "Moreno Valley Utility", "type": "POU", "territory": "PARTIAL — post-2004 development only; SCE serves the rest", "evRateStatus": "Not researched", "state": "California"},
  {"utility": "Gridley Electric Utility", "type": "POU", "territory": "City of Gridley, Butte Co.", "evRateStatus": "Not researched", "state": "California"},
  {"utility": "Needles Public Utility Authority", "type": "POU", "territory": "City of Needles, San Bernardino Co.", "evRateStatus": "Not researched", "state": "California"},
  {"utility": "Biggs Municipal Utilities", "type": "POU", "territory": "City of Biggs, Butte Co.", "evRateStatus": "Not researched", "state": "California"},
  {"utility": "Kirkwood Meadows PUD", "type": "POU", "territory": "Kirkwood ski area, Alpine/Amador/El Dorado", "evRateStatus": "Not researched", "state": "California"},
  {"utility": "Shelter Cove Resort Improvement District", "type": "POU", "territory": "Shelter Cove, Humboldt Co.", "evRateStatus": "Not researched", "state": "California"},
  {"utility": "Hetch Hetchy Power (SFPUC)", "type": "POU", "territory": "SF municipal, SFO, Muni, new development", "evRateStatus": "Not researched", "state": "California"},
  {"utility": "City of Vernon (Vernon Public Utilities)", "type": "POU", "territory": "Industrial city of Vernon, LA Co.", "evRateStatus": "Not researched", "state": "California"},
  {"utility": "Corona Department of Water & Power", "type": "POU", "territory": "PARTIAL — limited footprint; SCE serves most of Corona", "evRateStatus": "Not researched", "state": "California"},
  {"utility": "Victorville Municipal Utilities Services", "type": "POU", "territory": "SCLA & industrial Victorville; SCE serves the rest", "evRateStatus": "Not researched", "state": "California"},
  {"utility": "Island Energy (Pittsburg Power Co.)", "type": "POU", "territory": "Mare Island & Pittsburg", "evRateStatus": "Not researched", "state": "California"},
  {"utility": "Port of Oakland", "type": "POU", "territory": "Port & Oakland Airport tenants", "evRateStatus": "Not researched", "state": "California"},
  {"utility": "Port of Stockton", "type": "POU", "territory": "Port tenants, San Joaquin Co.", "evRateStatus": "Not researched", "state": "California"},
  {"utility": "City of Industry", "type": "POU", "territory": "Industrial city, LA Co.", "evRateStatus": "Not researched", "state": "California"},
  {"utility": "Cerritos Electric Utility", "type": "POU", "territory": "Cerritos businesses — SCE still DELIVERS. Verify", "evRateStatus": "Verify delivery tariff with SCE", "state": "California"},
  {"utility": "Lathrop Irrigation District", "type": "POU", "territory": "Parts of Lathrop, San Joaquin Co.", "evRateStatus": "Not researched", "state": "California"},
  {"utility": "Aha Macav Power Service (Fort Mojave)", "type": "Tribal", "territory": "Fort Mojave reservation near Needles", "evRateStatus": "Not researched", "state": "California"},
  {"utility": "Plumas-Sierra Rural Electric Cooperative", "type": "Co-op", "territory": "Plumas, Lassen, Sierra counties", "evRateStatus": "Not researched", "state": "California"},
  {"utility": "Anza Electric Cooperative", "type": "Co-op", "territory": "Anza, Aguanga, Garner Valley, Riverside Co.", "evRateStatus": "Not researched", "state": "California"},
  {"utility": "Surprise Valley Electrification Corp", "type": "Co-op", "territory": "Modoc & Lassen counties", "evRateStatus": "Not researched", "state": "California"},
  {"utility": "Valley Electric Association", "type": "Co-op", "territory": "Sliver of eastern Inyo Co. (44 customers)", "evRateStatus": "Not researched", "state": "California"},
  {"utility": "DTE Electric Company", "type": "IOU", "territory": "Southeast Michigan — Detroit, Ann Arbor, Port Huron", "evRateStatus": "Not researched here", "state": "Michigan"},
  {"utility": "Consumers Energy", "type": "IOU", "territory": "Most of the Lower Peninsula outside DTE", "evRateStatus": "Not researched here", "state": "Michigan"},
  {"utility": "Indiana Michigan Power (AEP)", "type": "IOU", "territory": "Southwest MI — Berrien, Cass, St Joseph", "evRateStatus": "Not researched here", "state": "Michigan"},
  {"utility": "UMERC — Upper Michigan Energy Resources (We Energies)", "type": "IOU", "territory": "Upper Peninsula — Marquette, Menominee", "evRateStatus": "Not researched here", "state": "Michigan"},
  {"utility": "UPPCO — Upper Peninsula Power Company", "type": "IOU", "territory": "Upper Peninsula", "evRateStatus": "Not researched here", "state": "Michigan"},
  {"utility": "Northern States Power — Xcel", "type": "IOU", "territory": "Western Upper Peninsula", "evRateStatus": "Not researched here", "state": "Michigan"},
  {"utility": "Alpena Power Company", "type": "IOU", "territory": "Alpena and surrounding townships", "evRateStatus": "Not researched here", "state": "Michigan"},
  {"utility": "Lansing Board of Water & Light", "type": "POU", "territory": "Lansing and East Lansing", "evRateStatus": "Not researched here", "state": "Michigan"},
  {"utility": "Holland Board of Public Works", "type": "POU", "territory": "City of Holland", "evRateStatus": "Not researched here", "state": "Michigan"},
  {"utility": "Traverse City Light & Power", "type": "POU", "territory": "City of Traverse City", "evRateStatus": "Not researched here", "state": "Michigan"},
  {"utility": "Coldwater Board of Public Utilities", "type": "POU", "territory": "City of Coldwater", "evRateStatus": "Not researched here", "state": "Michigan"},
  {"utility": "Wyandotte Municipal Services", "type": "POU", "territory": "City of Wyandotte", "evRateStatus": "Not researched here", "state": "Michigan"},
  {"utility": "Cloverland Electric Cooperative", "type": "Co-op", "territory": "Eastern Upper Peninsula", "evRateStatus": "Not researched here", "state": "Michigan"},
  {"utility": "Great Lakes Energy", "type": "Co-op", "territory": "Northwest Lower Peninsula", "evRateStatus": "Not researched here", "state": "Michigan"},
  {"utility": "Presque Isle Electric & Gas Co-op", "type": "Co-op", "territory": "Northeast Lower Peninsula", "evRateStatus": "Not researched here", "state": "Michigan"},
  {"utility": "HomeWorks Tri-County Electric", "type": "Co-op", "territory": "Central Lower Peninsula", "evRateStatus": "Not researched here", "state": "Michigan"},
  {"utility": "Midwest Energy & Communications", "type": "Co-op", "territory": "Southwest Lower Peninsula", "evRateStatus": "Not researched here", "state": "Michigan"},
  {"utility": "Thumb Electric Cooperative", "type": "Co-op", "territory": "The Thumb — Huron, Sanilac, Tuscola", "evRateStatus": "Not researched here", "state": "Michigan"},
  {"utility": "Other / not listed — enter manually", "type": "Other", "territory": "", "evRateStatus": "Enter the tariff manually", "state": ""},
];

/** Rate schedules the intake's Revenue tab offers. */
export const RATE_SCHEDULE_PICKER: string[] = ["BEV-1", "BEV-2-S", "BEV-2-P", "TOU-EV-7", "TOU-EV-8", "TOU-EV-9", "EV-HP >150kW", "EV-HP <150kW", "UMERC Cg1 — General Secondary, three-phase", "UMERC Cg5 — General Secondary Time-of-Use", "UMERC Cg3 — General Secondary Demand TOU", "Manual", "REU E2 — Small Commercial (no demand)", "REU E7/E8 — Large Commercial (demand)"];
