// Rebuilding the estimate from the intake-shaped tabs.
//
// The Quick Estimate's Build re-derives quantities, labour days, fees and
// rentals from the charger lines and distances. On the intake tabs those
// inputs change one field at a time and the estimate follows automatically,
// so a rebuild must not wipe what someone typed by hand on the Construction
// tab: every hand-typed field is recorded on project.sticky (a dot path) and
// restored after each rebuild. Clearing a sticky path hands the field back to
// the engine.

import { HARDWARE_ALLOWANCE, buildQuickProject, defaultQuickInput, normalizeQuickInput } from "../calc/autoplan";
import type { Project } from "../calc/types";
import { applyRemovalScope } from "../existing";
import { newId } from "../id";
import { applyFieldOverrides } from "../overrides";
import { applyEquipmentSchedule } from "../skus";

/** Fields a rebuild re-derives, which the intake tabs therefore let you pin. */
export const STICKY_PATHS = [
  "financial.laborBusinessDays",
  "financial.pmHours",
  "financial.pmPctOfLabor",
  "financial.autoCadDesignCost",
  "financial.electricalEngDesignCost",
  "financial.planCheckPermitFee",
  "peripherals.bollardsQty",
  "peripherals.adaVanQty",
  "peripherals.adaStdQty",
  "peripherals.adaAmbQty",
  "peripherals.adaRampCost",
  "peripherals.gfiTestQty",
  "peripherals.dumpWasteCost",
  "peripherals.permitFeeTotal",
  "peripherals.utilityAppFee",
  "peripherals.transformerPadCost",
  "peripherals.christyBoxQty",
  "peripherals.dataBoxQty",
  "peripherals.junctionBoxQty",
  "peripherals.gpr",
  "setup.scopeOfWork",
  "equipment",
] as const;
export type StickyPath = (typeof STICKY_PATHS)[number];

export const GPR_ITEM = "Private utility locating (GPR scan)";

type Bag = Record<string, unknown>;

export function readPath(project: Project, path: string): unknown {
  if (path === "equipment") return project.equipment;
  if (path === "peripherals.gpr") return (project.peripherals.customItems ?? []).find((c) => c.name === GPR_ITEM)?.qty ?? 0;
  const [section, key] = path.split(".");
  const bag = (project as unknown as Record<string, Bag>)[section];
  return bag ? bag[key] : undefined;
}

export function writePath(project: Project, path: string, value: unknown): Project {
  if (path === "equipment") return { ...project, equipment: Array.isArray(value) ? (value as Project["equipment"]).map((e) => ({ ...e })) : project.equipment };
  if (path === "peripherals.gpr") {
    const qty = typeof value === "number" ? value : 0;
    const items = (project.peripherals.customItems ?? []).filter((c) => c.name !== GPR_ITEM);
    const unitCost = (project.peripherals.customItems ?? []).find((c) => c.name === GPR_ITEM)?.unitCost ?? 1500;
    if (qty > 0) items.push({ name: GPR_ITEM, qty, unitCost });
    return { ...project, peripherals: { ...project.peripherals, customItems: items } };
  }
  const [section, key] = path.split(".");
  const bag = (project as unknown as Record<string, Bag>)[section];
  if (!bag) return project;
  return { ...project, [section]: { ...bag, [key]: value } } as Project;
}

export function isSticky(project: Pick<Project, "sticky">, path: string): boolean {
  return (project.sticky ?? []).includes(path);
}

/** Type a value into a rebuild-derived field: the value lands and the path is pinned. */
export function setSticky(project: Project, path: StickyPath, value: unknown): Project {
  const next = writePath(project, path, value);
  const sticky = new Set(next.sticky ?? []);
  sticky.add(path);
  return { ...next, sticky: [...sticky] };
}

/** Hand a pinned field back to the engine (the caller rebuilds afterwards). */
export function clearSticky(project: Project, path: string): Project {
  const sticky = (project.sticky ?? []).filter((p) => p !== path);
  return { ...project, sticky: sticky.length ? sticky : undefined };
}

/** Copy every pinned value from `before` onto `after`. */
export function restoreSticky(before: Project, after: Project): Project {
  let next = after;
  for (const path of before.sticky ?? []) next = writePath(next, path, readPath(before, path));
  return next;
}

/**
 * Can this project be regenerated from its Quick Estimate inputs? Yes when the
 * takeoff is empty or came from the generator (rows carry a genKey, or — for
 * projects built before the key existed — still read "<load type> #n"). A
 * takeoff typed row by row on the Takeoff tab is never regenerated by an
 * intake edit; the explicit rebuild button is the only way to replace it.
 */
export function canRebuild(project: Project): boolean {
  const rows = project.takeoff.filter((r) => !r.synthetic);
  if (rows.length === 0) return true;
  if (rows.some((r) => r.genKey || r.manual)) return true;
  return rows.every((r) => /^.+ #\d+$/.test(r.location) && r.location.startsWith(r.loadTypeId));
}

/**
 * Build (or rebuild) the estimate from the Quick Estimate inputs: the engine's
 * expansion, the price-book equipment schedule, the pinned fields, the
 * removal scope and the field-class overrides — in that order.
 */
export function rebuildProject(project: Project, allowance: Record<string, number> = HARDWARE_ALLOWANCE): Project {
  const quick = project.quick ? normalizeQuickInput(project.quick, project.setup) : defaultQuickInput();
  let next = buildQuickProject(quick, project, newId("qs"), allowance);
  next = applyEquipmentSchedule(next, allowance);
  next = restoreSticky(project, next);
  next = applyRemovalScope(next);
  next = applyFieldOverrides(next);
  return next;
}
