"""Exception hierarchy.

Every exception carries a plain-language `message` suitable for showing to an
operator in the GUI. Never surface a traceback to the user; catch these at the
CLI / GUI boundary and print `.message`.
"""

from __future__ import annotations


class ProposalError(Exception):
    """Base for every error this program raises deliberately."""

    def __init__(self, message: str, *, detail: str | None = None) -> None:
        super().__init__(message)
        self.message = message
        self.detail = detail

    def __str__(self) -> str:  # pragma: no cover - trivial
        return self.message if not self.detail else f"{self.message} ({self.detail})"


class FingerprintMismatch(ProposalError):
    """The workbook does not look like a supported version."""


class UnknownEngine(ProposalError):
    """`Updated Chargers Revenue Calcul`!B3 held something unrecognised."""


class FieldNotFound(ProposalError):
    """resolve() exhausted defined name, label search and fixed cell."""


class WorkbookNotCalculated(ProposalError):
    """openpyxl found no cached values. Excel must recalculate and re-save.

    openpyxl cannot evaluate formulas; it only reads the result Excel cached the
    last time the file was saved. A workbook saved with calculation suspended,
    or generated by a non-Excel writer, has no cached values at all.
    """

    DEFAULT = (
        "This workbook has no cached values. Open it in Excel, press "
        "Ctrl+Alt+F9, save, and try again."
    )

    def __init__(self, message: str | None = None, *, detail: str | None = None) -> None:
        super().__init__(message or self.DEFAULT, detail=detail)


class ValidationFailed(ProposalError):
    """One or more ERROR-level validations tripped. Nothing was written."""

    def __init__(self, message: str, findings: list | None = None) -> None:
        super().__init__(message)
        self.findings = findings or []


class TemplateMismatch(ProposalError):
    """The template and the field map disagree about which tokens exist."""


class OutputNotWritable(ProposalError):
    r"""The document could not be written where it was asked to go.

    Three causes, in the order they actually happen:

    1. **The last proposal is still open in Word.** Word holds an exclusive lock
       on the .docx, so re-generating over it fails. By far the most common.
    2. **OneDrive folder backup.** The real Documents is `%OneDrive%\Documents`
       and `%USERPROFILE%\Documents` is a redirected stub. `paths.documents_dir()`
       reads the true path from the registry, but a folder mid-sync can still
       refuse a write.
    3. **Defender Controlled Folder Access.** Documents is a protected folder by
       default and this .exe is not code-signed, so Defender blocks it outright
       with no prompt and no entry the operator would think to look for.

    A bare "permission denied" tells the operator none of that, which is exactly
    what happened the first time this shipped to another machine.
    """

    @classmethod
    def for_path(cls, path, cause: Exception) -> "OutputNotWritable":
        return cls(
            f"Could not write {path}. Three things cause this, in order of how "
            f"often: the previous proposal is still open in Word (close it and "
            f"press Generate again); OneDrive is mid-sync on that folder; or "
            f"Windows Defender's Controlled Folder Access is blocking this app, "
            f"which it does silently because the app is not code-signed. To "
            f"clear the last one, open Windows Security > Virus & threat "
            f"protection > Ransomware protection > Allow an app through "
            f"Controlled folder access, and add EVProposalGenerator.exe.",
            detail=f"{type(cause).__name__}: {cause}",
        )


class WorkbookNotReadable(ProposalError):
    r"""The .xlsx itself could not be opened.

    This surfaces the moment a file is dropped, before anything is written, so
    it is NOT the output-folder problem. On Windows a read that fails with
    "permission denied" is almost always one of:

    1. **The workbook is open in Excel.** Excel usually permits a concurrent
       read, but not while it is mid-save, and not at all for some
       OneDrive/AutoSave states. The tell is a `~$name.xlsx` lock file beside it.
    2. **A OneDrive "online-only" placeholder.** With Files On-Demand the file
       exists in Explorer at full size but no bytes are local; opening it forces
       a download that fails outright when OneDrive is paused, signed out, or
       offline. The tell is the OFFLINE / RECALL_ON_DATA_ACCESS attribute.
    3. **Dragged out of Outlook or a zip preview.** The path lands under
       `%TEMP%\Content.Outlook\...`, which is ACL'd and often already gone.
       The tell is a temp path.

    `diagnose()` checks all three against the actual file so the operator is
    told which one it is, instead of the bare "permission denied" that shipped.
    """

    @classmethod
    def diagnose(cls, path, cause: Exception) -> "WorkbookNotReadable":
        import os

        path = __import__("pathlib").Path(path)
        clues: list[str] = []

        if not path.exists():
            clues.append(
                "the file is not there any more - if it was dragged out of "
                "Outlook or a zip preview, Windows deletes the temporary copy. "
                "Save it to a real folder first, then drag it in"
            )
        else:
            lock = path.with_name("~$" + path.name)
            if lock.exists():
                clues.append(
                    f"'{path.name}' is open in Excel right now ({lock.name} is "
                    "beside it). Close it in Excel and drag it in again"
                )

            # OneDrive Files On-Demand: present in Explorer, no bytes on disk.
            OFFLINE, RECALL_OPEN, RECALL_DATA = 0x1000, 0x40000, 0x400000
            try:
                attrs = os.stat(path, follow_symlinks=False).st_file_attributes
                if attrs & (OFFLINE | RECALL_OPEN | RECALL_DATA):
                    clues.append(
                        "this file is 'online-only' in OneDrive - it shows a "
                        "cloud icon in Explorer and none of it is on this "
                        "machine. Right-click it, choose 'Always keep on this "
                        "device', wait for the green tick, then drag it in"
                    )
            except (AttributeError, OSError):
                pass

            if path.is_dir():
                clues.append(
                    "that path is a folder, not a spreadsheet - drag the .xlsx "
                    "file itself rather than the folder holding it"
                )

            # Only the folders Outlook and Explorer's zip viewer actually use.
            # A bare "is it under %TEMP%" test is too broad and mislabels
            # anything a user happens to keep there.
            lowered = os.path.realpath(path).lower()
            if any(mark in lowered for mark in (
                "content.outlook", "inetcache", "temporary internet files",
                "\temp\7z", "\temp\rar$",
            )):
                clues.append(
                    "it was opened straight out of an email or a zip, so it "
                    "lives in a temporary folder Windows locks down and clears. "
                    "Save it to Documents or the Desktop first, then drag that "
                    "copy in"
                )

        if not clues:
            clues.append(
                "the file is there but this program was refused access to it. "
                "Check it is not open in another program, and that it is not on "
                "a network drive this machine cannot reach"
            )

        return cls(
            f"Could not read {path.name}: " + "; also ".join(clues) + ".",
            detail=f"{type(cause).__name__}: {cause}",
        )

